'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import ChatWindow from '@/components/chat/ChatWindow';
import ModelCompareView, { type CompareLaneView } from '@/components/chat/ModelCompareView';
import PromptInput, { type PromptSubmitPayload } from '@/components/chat/PromptInput';
import {
  createInitialStreamState,
  createSessionStreamController,
  type StreamState
} from '@/lib/streaming';
import { generateSessionTitle, isAutoGeneratedSessionName } from '@/lib/sessionTitle';
import { estimateTokenCount } from '@/lib/tokenize';
import { useModelsStore } from '@/store/models';
import { useWorkspaceStore } from '@/store/workspace';
import type { StreamRequest } from '@/types/ipc';
import type { ChatMessage } from '@/types/message';
import type { SessionParameters, SessionStatus } from '@/types/session';
import { Switch } from '@/components/ui';
import PanelHeader from './PanelHeader';

interface SessionPanelProps {
  sessionId: string;
  panelTitle: string;
}

/**
 * Renders a single session panel surface.
 */
export default function SessionPanel({ sessionId, panelTitle }: SessionPanelProps): React.JSX.Element {
  const controllerRef = useRef<ReturnType<typeof createSessionStreamController> | null>(null);
  const committedOutputRef = useRef('');
  const activeInputTokensRef = useRef(0);
  const activeAttachedFilesRef = useRef<string[]>([]);
  const compareControllersRef = useRef<Map<string, ReturnType<typeof createSessionStreamController>>>(new Map());
  const compareCommittedOutputsRef = useRef<Map<string, string>>(new Map());

  const ensureSession = useWorkspaceStore((state) => state.ensureSession);
  const appendMessage = useWorkspaceStore((state) => state.appendMessage);
  const clearMessages = useWorkspaceStore((state) => state.clearMessages);
  const updateSessionParameters = useWorkspaceStore((state) => state.updateSessionParameters);
  const updateSessionName = useWorkspaceStore((state) => state.updateSessionName);
  const updateSessionModel = useWorkspaceStore((state) => state.updateSessionModel);
  const updatePanelStatus = useWorkspaceStore((state) => state.updatePanelStatus);
  const session = useWorkspaceStore((state) => state.sessions.get(sessionId));

  const [streamState, setStreamState] = useState<StreamState>(createInitialStreamState(sessionId));
  const [comparePrompt, setComparePrompt] = useState('');
  const [compareLaneStates, setCompareLaneStates] = useState<Map<string, StreamState>>(new Map());
  const ollamaModels = useModelsStore((state) => state.ollamaModels);
  const refreshOllamaModels = useModelsStore((state) => state.refreshOllamaModels);
  const getModelOptions = useModelsStore((state) => state.getModelOptions);

  useEffect(() => {
    ensureSession(sessionId);
  }, [ensureSession, sessionId]);

  const provider = 'ollama' as const;
  const modelId = session?.modelId ?? '';
  const params: SessionParameters =
    session?.parameters ?? {
      advancedMode: false,
      projectMode: false,
      compareMode: false,
      compareModelIds: [],
      lastTemplateId: undefined,
      temperature: 0.7,
      maxTokens: 1024,
      topP: 1,
      frequencyPenalty: 0,
      systemPrompt: '',
      rawJsonMode: false,
      rawJsonPayload: ''
    };
  const messages: ChatMessage[] = session?.messages ?? [];

  const modelOptions = useMemo<Array<{ id: string; name: string }>>(() => {
    return ollamaModels.length > 0 ? ollamaModels : getModelOptions(provider);
  }, [getModelOptions, ollamaModels, provider]);

  const compareLaneConfigs = useMemo(
    () =>
      (params.compareModelIds.length > 0 ? params.compareModelIds : [modelId, modelOptions[0]?.id ?? ''])
        .filter((value, index, array): value is string => Boolean(value) && array.indexOf(value) === index)
        .slice(0, 2)
        .map((value, index) => ({
          laneId: `lane-${index + 1}`,
          modelId: value
        })),
    [modelId, modelOptions, params.compareModelIds]
  );

  const compareLanesView = useMemo<CompareLaneView[]>(
    () =>
      compareLaneConfigs.map((lane) => ({
        id: lane.laneId,
        modelId: lane.modelId,
        streamState: compareLaneStates.get(lane.laneId) ?? createInitialStreamState(`${sessionId}:${lane.laneId}`)
      })),
    [compareLaneConfigs, compareLaneStates, sessionId]
  );

  const isCompareStreaming = useMemo(
    () =>
      params.compareMode &&
      Array.from(compareLaneStates.values()).some(
        (laneState) => laneState.phase === 'starting' || laneState.phase === 'streaming'
      ),
    [compareLaneStates, params.compareMode]
  );

  const status = useMemo<SessionStatus>(() => {
    if (params.compareMode) {
      if (isCompareStreaming) {
        const hasStarting = Array.from(compareLaneStates.values()).some((laneState) => laneState.phase === 'starting');
        return hasStarting ? 'loading-models' : 'streaming';
      }

      if (Array.from(compareLaneStates.values()).some((laneState) => laneState.phase === 'error')) {
        return 'error';
      }

      return 'idle';
    }

    switch (streamState.phase) {
      case 'starting':
        return 'loading-models';
      case 'streaming':
        return 'streaming';
      case 'done':
        return 'done';
      case 'canceled':
        return 'canceled';
      case 'error':
        return 'error';
      default:
        return 'idle';
    }
  }, [compareLaneStates, isCompareStreaming, params.compareMode, streamState.phase]);

  const isStreaming = params.compareMode ? isCompareStreaming : streamState.phase === 'starting' || streamState.phase === 'streaming';

  useEffect(() => {
    updatePanelStatus(sessionId, status);
  }, [sessionId, status, updatePanelStatus]);

  useEffect(() => {
    if (!session) {
      return;
    }

    if (!session.modelId && modelOptions[0]?.id) {
      updateSessionModel(sessionId, modelOptions[0].id);
      return;
    }

    if (session.modelId && !modelOptions.some((model) => model.id === session.modelId) && modelOptions[0]?.id) {
      updateSessionModel(sessionId, modelOptions[0].id);
    }
  }, [modelOptions, session, sessionId, updateSessionModel]);

  useEffect(() => {
    void refreshOllamaModels();
    const interval = window.setInterval(() => {
      void refreshOllamaModels();
    }, 30000);

    return () => {
      window.clearInterval(interval);
    };
  }, [refreshOllamaModels]);

  useEffect(() => {
    if (streamState.phase === 'done' && streamState.output && committedOutputRef.current !== streamState.output) {
      committedOutputRef.current = streamState.output;

      const startMs = streamState.startedAt ? new Date(streamState.startedAt).getTime() : Number.NaN;
      const endMs = streamState.completedAt ? new Date(streamState.completedAt).getTime() : new Date().getTime();
      const responseMs =
        Number.isFinite(startMs) && Number.isFinite(endMs)
          ? Math.max(0, endMs - startMs)
          : 0;

      appendMessage(sessionId, {
        id: crypto.randomUUID(),
        role: 'assistant',
        content: streamState.output,
        createdAt: new Date().toISOString(),
        metadata: {
          inputTokens: activeInputTokensRef.current,
          outputTokens: estimateTokenCount(streamState.output),
          responseMs,
          attachedFiles: activeAttachedFilesRef.current
        }
      });
    }
  }, [appendMessage, sessionId, streamState]);

  useEffect(() => {
    const compareControllers = compareControllersRef.current;

    return () => {
      controllerRef.current?.dispose();
      controllerRef.current = null;

      for (const controller of compareControllers.values()) {
        controller.dispose();
      }
      compareControllers.clear();
    };
  }, []);

  useEffect(() => {
    if (!params.compareMode) {
      return;
    }

    for (const lane of compareLaneConfigs) {
      const laneState = compareLaneStates.get(lane.laneId);
      if (!laneState || laneState.phase !== 'done' || !laneState.output) {
        continue;
      }

      const committed = compareCommittedOutputsRef.current.get(lane.laneId);
      if (committed === laneState.output) {
        continue;
      }

      compareCommittedOutputsRef.current.set(lane.laneId, laneState.output);
      appendMessage(sessionId, {
        id: crypto.randomUUID(),
        role: 'assistant',
        content: laneState.output,
        createdAt: new Date().toISOString(),
        metadata: {
          comparedModelId: lane.modelId,
          attachedFiles: activeAttachedFilesRef.current
        }
      });
    }
  }, [appendMessage, compareLaneConfigs, compareLaneStates, params.compareMode, sessionId]);

  const clearSession = (): void => {
    clearMessages(sessionId);
    setStreamState(createInitialStreamState(sessionId));
    setCompareLaneStates(new Map());
    setComparePrompt('');
    committedOutputRef.current = '';
    activeAttachedFilesRef.current = [];
    compareCommittedOutputsRef.current.clear();
  };

  const cancelStream = async (): Promise<void> => {
    if (params.compareMode) {
      const cancellations = Array.from(compareControllersRef.current.values()).map((controller) => controller.cancel());
      await Promise.allSettled(cancellations);
      return;
    }

    if (!controllerRef.current) {
      return;
    }

    await controllerRef.current.cancel();
  };

  const stopService = async (): Promise<void> => {
    const bridge = (window as unknown as { modeldeck?: Window['modeldeck'] }).modeldeck;

    if (controllerRef.current) {
      await controllerRef.current.cancel();
    }

    if (bridge) {
      await bridge.ollama.stopService();
    }

    clearSession();
  };

  const submitPrompt = async (payload: PromptSubmitPayload): Promise<void> => {
    if (!modelId) {
      setStreamState((previous) => ({
        ...previous,
        phase: 'error',
        error: 'No Ollama model is installed. Download a model from Model Library first.',
        updatedAt: new Date().toISOString()
      }));
      return;
    }

    const inputTokens = estimateTokenCount(payload.prompt);
    activeInputTokensRef.current = inputTokens;
    const attachedFileNames = payload.attachments.map((file) => file.name);
    activeAttachedFilesRef.current = attachedFileNames;

    const userMessage: ChatMessage = {
      id: crypto.randomUUID(),
      role: 'user',
      content: payload.prompt,
      createdAt: new Date().toISOString(),
      metadata: {
        inputTokens,
        attachmentCount: payload.attachments.length,
        attachedFiles: attachedFileNames
      }
    };
    appendMessage(sessionId, userMessage);

    const conversationForTitle = [...messages, userMessage];
    const shouldAutoRename =
      !session ||
      isAutoGeneratedSessionName(session.name, session.id) ||
      session.messages.length < 4;

    if (shouldAutoRename) {
      updateSessionName(sessionId, generateSessionTitle(conversationForTitle));
    }

    if (payload.parameters.compareMode) {
      const lanes = compareLaneConfigs.length >= 2 ? compareLaneConfigs : [];
      if (lanes.length < 2) {
        setStreamState((previous) => ({
          ...previous,
          phase: 'error',
          error: 'Select two models to start comparison mode.',
          updatedAt: new Date().toISOString()
        }));
        return;
      }

      setComparePrompt(payload.prompt);
      compareCommittedOutputsRef.current.clear();

      for (const controller of compareControllersRef.current.values()) {
        controller.dispose();
      }
      compareControllersRef.current.clear();

      setCompareLaneStates(new Map());

      const laneControllers = lanes.map((lane) => {
        const laneSessionId = `${sessionId}:${lane.laneId}:${crypto.randomUUID()}`;
        const laneRequest: StreamRequest = {
          sessionId: laneSessionId,
          modelId: lane.modelId,
          prompt: payload.prompt,
          attachments: payload.attachments,
          projectMode: payload.projectMode,
          systemPrompt: payload.parameters.systemPrompt,
          temperature: payload.parameters.temperature,
          maxTokens: payload.parameters.maxTokens,
          topP: payload.parameters.topP,
          frequencyPenalty: payload.parameters.frequencyPenalty,
          rawJsonPayload: payload.parameters.rawJsonMode ? payload.parameters.rawJsonPayload : undefined
        };

        const controller = createSessionStreamController({
          sessionId: laneSessionId,
          provider,
          payload: laneRequest,
          onStateChange: (laneState) => {
            setCompareLaneStates((previous) => {
              const next = new Map(previous);
              next.set(lane.laneId, laneState);
              return next;
            });
          }
        });

        compareControllersRef.current.set(lane.laneId, controller);
        return { laneId: lane.laneId, controller };
      });

      const results = await Promise.all(
        laneControllers.map(async (entry) => ({
          laneId: entry.laneId,
          response: await entry.controller.start()
        }))
      );

      for (const result of results) {
        if (!result.response.success) {
          setCompareLaneStates((previous) => {
            const next = new Map(previous);
            const current = next.get(result.laneId) ?? createInitialStreamState(`${sessionId}:${result.laneId}`);
            next.set(result.laneId, {
              ...current,
              phase: 'error',
              error: result.response.error ?? 'Failed to start compare stream.',
              updatedAt: new Date().toISOString()
            });
            return next;
          });
        }
      }
      return;
    }

    const request: StreamRequest = {
      sessionId,
      modelId,
      prompt: payload.prompt,
      attachments: payload.attachments,
      projectMode: payload.projectMode,
      systemPrompt: payload.parameters.systemPrompt,
      temperature: payload.parameters.temperature,
      maxTokens: payload.parameters.maxTokens,
      topP: payload.parameters.topP,
      frequencyPenalty: payload.parameters.frequencyPenalty,
      rawJsonPayload: payload.parameters.rawJsonMode ? payload.parameters.rawJsonPayload : undefined
    };

    controllerRef.current?.dispose();
    controllerRef.current = createSessionStreamController({
      sessionId,
      provider,
      payload: request,
      onStateChange: setStreamState
    });
    committedOutputRef.current = '';

    const response = await controllerRef.current.start();
    if (!response.success) {
      setStreamState((previous) => ({
        ...previous,
        phase: 'error',
        error: response.error ?? 'Failed to start stream.',
        updatedAt: new Date().toISOString()
      }));
    }
  };

  return (
    <section className="flex min-h-0 h-full flex-col overflow-hidden rounded-xl border border-zinc-800 bg-zinc-950">
      <PanelHeader
        modelId={modelId}
        modelOptions={modelOptions}
        status={status}
        isStreaming={isStreaming}
        onModelChange={(nextModelId) => {
          updateSessionModel(sessionId, nextModelId);
        }}
        onCancelStream={() => {
          void cancelStream();
        }}
        onStopService={() => {
          void stopService();
        }}
        onClearSession={clearSession}
      />

      <div className="border-b border-zinc-800 bg-zinc-950/80 px-4 py-2">
        <div className="mx-auto flex w-full max-w-3xl flex-wrap items-center gap-2">
          <div className="inline-flex items-center gap-2 rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-1">
            <span className="text-xs uppercase tracking-wider text-zinc-300">Compare Mode</span>
            <Switch
              checked={params.compareMode}
              onCheckedChange={(checked) => {
                const nextCompareModels =
                  params.compareModelIds.length > 0
                    ? params.compareModelIds
                    : [modelId, modelOptions[0]?.id ?? ''].filter(Boolean);

                updateSessionParameters(sessionId, {
                  ...params,
                  compareMode: checked,
                  compareModelIds: nextCompareModels
                });
                if (!checked) {
                  setCompareLaneStates(new Map());
                  setComparePrompt('');
                }
              }}
            />
          </div>

          {params.compareMode ? (
            <>
              {[0, 1].map((index) => {
                const selected = params.compareModelIds[index] ?? modelOptions[index]?.id ?? '';
                return (
                  <select
                    key={`compare-model-${index}`}
                    value={selected}
                    onChange={(event) => {
                      const next = [...params.compareModelIds];
                      next[index] = event.target.value;
                      updateSessionParameters(sessionId, {
                        ...params,
                        compareModelIds: next.filter(Boolean)
                      });
                    }}
                    className="modeldeck-select rounded-lg border border-zinc-700 bg-zinc-900 px-2 py-1 text-sm text-zinc-100"
                  >
                    {modelOptions.map((option) => (
                      <option key={`${index}-${option.id}`} value={option.id}>
                        {index + 1}. {option.name}
                      </option>
                    ))}
                  </select>
                );
              })}
            </>
          ) : null}
        </div>
      </div>

      {params.compareMode ? (
        <ModelCompareView lanes={compareLanesView} latestPrompt={comparePrompt} />
      ) : (
        <ChatWindow
          messages={messages}
          streamState={streamState}
          session={session ?? {
            id: sessionId,
            name: 'New chat',
            provider,
            modelId,
            messages,
            parameters: params,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
          }}
        />
      )}

      <PromptInput
        params={params}
        disabled={isStreaming}
        onParamsChange={(next) => {
          updateSessionParameters(sessionId, next);
        }}
        onSubmit={(payload) => {
          void submitPrompt(payload);
        }}
      />
    </section>
  );
}
