import type { ChatMessage } from '@/types/message';

const STOP_WORDS = new Set([
  'a',
  'an',
  'and',
  'are',
  'as',
  'at',
  'be',
  'by',
  'can',
  'do',
  'for',
  'from',
  'how',
  'i',
  'in',
  'is',
  'it',
  'like',
  'me',
  'my',
  'of',
  'on',
  'or',
  'please',
  'the',
  'to',
  'we',
  'with',
  'you',
  'your'
]);

/**
 * Returns true if a session title still looks auto-generated/generic.
 */
export function isAutoGeneratedSessionName(name: string | undefined, sessionId: string): boolean {
  const value = (name ?? '').trim();
  if (!value) {
    return true;
  }

  if (value.toLowerCase() === 'new chat' || value.toLowerCase() === 'untitled chat') {
    return true;
  }

  return value === `Session ${sessionId.slice(0, 8)}`;
}

/**
 * Generates a concise topic title from the first part of the conversation.
 */
export function generateSessionTitle(messages: ChatMessage[]): string {
  const conversationSeed = messages
    .filter((message) => message.role === 'user' || message.role === 'assistant')
    .slice(0, 6)
    .map((message) => message.content)
    .join(' ')
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/`[^`]*`/g, ' ')
    .replace(/https?:\/\/\S+/g, ' ')
    .replace(/[^a-zA-Z0-9\s-]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

  if (!conversationSeed) {
    return 'New chat';
  }

  const rawWords = conversationSeed
    .toLowerCase()
    .split(/\s+/)
    .map((word) => word.trim())
    .filter((word) => word.length >= 3 && !STOP_WORDS.has(word));

  if (rawWords.length === 0) {
    return 'New chat';
  }

  const frequency = new Map<string, { count: number; firstIndex: number }>();
  rawWords.forEach((word, index) => {
    const current = frequency.get(word);
    if (!current) {
      frequency.set(word, { count: 1, firstIndex: index });
      return;
    }

    frequency.set(word, { count: current.count + 1, firstIndex: current.firstIndex });
  });

  const ranked = Array.from(frequency.entries())
    .sort((left, right) => {
      if (right[1].count !== left[1].count) {
        return right[1].count - left[1].count;
      }

      return left[1].firstIndex - right[1].firstIndex;
    })
    .slice(0, 6)
    .map(([word]) => word);

  const title = ranked
    .map((word) => `${word[0]?.toUpperCase() ?? ''}${word.slice(1)}`)
    .join(' ')
    .trim();

  return title || 'New chat';
}
